### ISSUE TITLE
Program/pi crashes every now and then

### ISSUE THREAD

**Issue by CuriousJames** [Jonty/Oust#10]
When playing it at EMF 2016 we experienced the system stopping several times in an hour, a reboot of the pi restored play.

It may be related to controller range - if someone seemed to get a little further than normal that controller looses it's light (it won't be illuminated at all) and no vibration is felt, and then all the other controllers within the next few seconds (though not all at once) do the same.

**Comment by Jonty** [comment]
Aha! I've not tested going out of range in the current build on that hardware - I'll have a look. Thanks!

**Comment by Jonty** [comment]
Fixed by 2cce4d6a1d4d53240638c6006ab3697fa853e8b5, hopefully.
