### ISSUE TITLE
Fix the bluetooth pairing problem properly

### ISSUE THREAD

**Issue by Jonty** [Jonty/Oust#3]
Hurrah for kernel bugs. @marksteward wants to tackle this.

https://github.com/torvalds/linux/commit/432df05

**Comment by adangert** [comment]
Although this doesn't fix the scan_enable.sh, changing line 92 in /usr/bin/bluez-simple-agent to
capability = "DisplayYesNo"
I think this allowed for me to pair the controllers automatically and wirelessly (as long as they have been paired before) with the raspberry pi. perhaps I didn't notice it was already doing that before, but controller pairing is pretty much flawless for me now.

**Comment by Jonty** [comment]
@aangert Interesting! I'll have a play with that and see how it affects things, how did you find that out?

**Comment by adangert** [comment]
@Jonty I've been working on adding sound/music support, and the unintended side effect of trying to pair my speakers over bluetooth, including that line change, seemed to improve the initial connection to the move controllers, a happy accident perhaps? haha

**Comment by Jonty** [comment]
Fixed by @hdsjulian!
